tap railwaycat/emacsmacport
tap sanemat/font

install aspell --with-lang-en || true
install awscli || true
install cmigemo || true
install colordiff || true
install ctags || true
install direnv || true
install emacs-mac --icon-official || true
install fontforge || true
install ghq || true
install ghostscript || true
install git || true
install global || true
install gnuplot || true
install gnu-sed || true
install go || true
install gradle
install graphicsmagick || true
install graphviz || true
install httpie || true
install hub || true
install imagemagick || true
install jo || true
install jq || true
install markdown || true
install mecab || true
install mecab-ipadic || true
install memcached || true
install mercurial || true
install mongodb || true
install mysql || true
install nginx || true
install nkf || true
install openssl || true
install peco || true
install phantomjs || true
install plantuml || true
install readline || true
install reattach-to-user-namespace || true
install redis || true
install ricty --powerline --vim-powerline || true
install rlwrap || true
install source-highlight || true
install sqlite || true
install ssh-copy-id || true
install terminal-notifier || true
install the_silver_searcher || true
install tig || true
install tmux || true
install tmux-cssh || true
install tree || true
install vim || true
install w3m || true
install watch || true
install wget || true
install zsh || true

cleanup
