tap railwaycat/emacsmacport
tap sanemat/font

install aspell --with-lang-en
install awscli
install cmigemo
install colordiff
install ctags
install dep
install direnv
install emacs-mac --with-gnutls --with-official-icon
install envchain
install fontforge
install ghq
install ghostscript
install git
install glide
install global
install gnuplot
install gnu-sed
install go
install gpg-agent
install gradle
install graphicsmagick
install graphviz
install htop
install httpie
install hub
install imagemagick
install jo
install jq
install markdown
install mecab
install mecab-ipadic
install memcached
install mercurial
install mongodb
install mysql
install nginx
install nkf
install openssl
install parallel
install peco
install phantomjs
install pinentry-mac
install plantuml
install readline
install reattach-to-user-namespace
install redis
install ricty --powerline --vim-powerline
install rlwrap
install source-highlight
install sqlite
install ssh-copy-id
install terminal-notifier
install the_silver_searcher
install tig
install tmux
install tmux-cssh
install tree
install vim
install watch
install wget
install zsh

cask install google-cloud-sdk
cask install minikube

cleanup
